env:
  contexts:
    - name: Default Context
      urls:
        - http://54.179.2.8:4002
      includePaths:
        - http://54.179.2.8:4002/.*

authentication:
  method: json
  parameters:
    loginPageUrl: http://54.179.2.8:4002
    loginRequestUrl: http://54.179.2.8:4002/api/auth/login
    loginRequestBody: '{ "email": "%username%", "password": "%password%" }'
    loginRequestHeaders: Content-Type: application/json
  verification:
    method: poll
    parameters:
      pollUrl: http://54.179.2.8:4002/api/order
      pollFrequency: 10
      pollUnits: seconds
      loggedInRegex: '"message"\\s*:\\s*"Berhasil mengambil data orders"'
      loggedOutRegex: '"message"\\s*:\\s*"Token tidak valid"'

sessionManagement:
  method: httpAuthentication
  parameters: {}

users:
  - name: authentication user
    credentials:
      username: rajif@gmail.com
      password: mypassword

jobs:
  - name: spider
    type: spider
    parameters:
      context: Default Context
      user: authentication user
      maxDepth: 3
      maxDuration: 2
      acceptCookies: true
      parseComments: true
      parseRobotsTxt: true
      parseSitemapXml: true

  - name: openapi
    type: openapi
    parameters:
      apiFile: /config/src/swagger-output.json
      context: Default Context
      targetUrl: http://54.179.2.8:4002

  - name: activeScan
    type: activeScan
    parameters:
      context: Default Context
      user: authentication user
      maxRuleDurationInMins: 2
      maxScanDurationInMins: 10
      threadPerHost: 2
      delayInMs: 500

  - name: report
    type: report
    parameters:
      template: traditional-json-plus
      reportTitle: "DAST Security Report - StarHub Express"
      reportDescription: "Dynamic Application Security Testing untuk aplikasi StarHub Express API"
      reportDir: /output
      reportFile: ZAP-Report

  - name: export
    type: export
    parameters:
      fileName: /output/ZAP-Sites-Tree.yaml
      type: YAML
      source: "Sites Tree"