env:
    contexts:
    -
        excludePaths: []
        includePaths:
        - http://13.212.48.92:4003.*
        name: Default Context
        technology:
            exclude: []
        urls:
        - http://13.212.48.92:4003
        authentication:
            method: form
            parameters:
                loginPageUrl: http://13.212.48.92:4003/api/auth/login
                loginRequestBody: username={%username%}&password={%password%}
                loginRequestUrl: http://13.212.48.92:4003/api/auth/login
            verification:
                method: poll
                loggedInRegex: Login
                loggedOutRegex: Loggout
                pollFrequency: 60
                pollUnits: requests
                pollUrl: http://13.212.48.92:4003/api/auth/login
        sessionManagement:
            method: cookie
            parameters: {}
        users:
        -
            credentials:
                password: mypassword
                username: rajif@gmail.com
            name: authentication user
    vars: {}
    parameters:
        failOnError: true
        failOnWarning: false
        progressToStdout: true
jobs:
-
    parameters:
        scanOnlyInScope: true
        enableTags: false
    rules: []
    name: passiveScan-config
    type: passiveScan-config
-
    name: openapi
    parameters:
        apiFile: /demo/swagger_api.yaml
        context: Default Context
    type: openapi
-
    parameters: {}
    name: passiveScan-wait
    type: passiveScan-wait
-
    parameters:
        context: Default Context
        threadPerHost: 4
        user: authentication user
    policyDefinition:
        rules: []
    name: activeScan
    type: activeScan
