env:
  contexts:
    - name: Default Context
      includePaths:
        - http://13.212.48.92:4003.*
      urls:
        - http://13.212.48.92:4003
      authentication:
        method: form
        parameters:
          loginPageUrl: http://13.212.48.92:4003/api/auth/login
          loginRequestUrl: http://13.212.48.92:4003/api/auth/login
          loginRequestBody: username={%username%}&password={%password%}
        verification:
          method: poll
          pollUrl: http://13.212.48.92:4003/api/auth/login
          loggedInRegex: Login
          loggedOutRegex: Loggout
          pollFrequency: 60
          pollUnits: requests
      sessionManagement:
        method: cookie
        parameters: {}
      users:
        - name: authentication user
          credentials:
            username: rajif@gmail.com
            password: mypassword

  vars: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - name: explore-request
    type: request
    parameters:
      requests:
        - url: http://13.212.48.92:4003/api/auth/login
          method: POST
          headers:
            Content-Type: application/x-www-form-urlencoded
          body: username=rajif@gmail.com&password=mypassword

        - url: http://13.212.48.92:4003/api/auth/register
          method: POST
          headers:
            Content-Type: application/json
          body: '{"username": "newuser", "email": "newuser@gmail.com", "password": "test123"}'

        - url: http://13.212.48.92:4003/api/order
          method: POST
          headers:
            Content-Type: application/json
          body: '{"productId": "12345", "quantity": 1}'

  - name: activeScan
    type: activeScan
    parameters:
      context: Default Context
      user: authentication user
      threadPerHost: 4
    policyDefinition:
      rules: []
