jobs:
  - name: passiveScan-config
    type: passiveScan-config
    parameters:
      scanOnlyInScope: true
      enableTags: false
    rules: []

  # Aktifkan salah satu dari ini:
  - name: explore-request
    type: request
    parameters:
      requests:
        - url: http://13.212.48.92:4003/api/users
          method: GET
          context: Default Context
          user: authentication user

  # Optional, jika ada Swagger
  # - name: openapi
  #   type: openapi
  #   parameters:
  #     definitionUrl: http://13.212.48.92:4003/swagger
  #     context: Default Context

  - name: passiveScan-wait
    type: passiveScan-wait
    parameters: {}

  - name: activeScan
    type: activeScan
    parameters:
      context: Default Context
      threadPerHost: 4
      user: authentication user
    policyDefinition:
      rules: []
