env:
  contexts:
    - name: Default Context
      includePaths:
        - http://13.212.48.92:4003.*
      excludePaths: []
      urls:
        - http://13.212.48.92:4003
      technology:
        exclude: []
      authentication:
        method: form
        parameters:
          loginPageUrl: http://13.212.48.92:4003/api/auth/login
          loginRequestBody: username={%username%}&password={%password%}
          loginRequestUrl: http://13.212.48.92:4003/api/auth/login
        verification:
          method: poll
          loggedInRegex: Login
          loggedOutRegex: Loggout
          pollFrequency: 60
          pollUnits: requests
          pollUrl: http://13.212.48.92:4003/api/auth/login
      sessionManagement:
        method: cookie
        parameters: {}
      users:
        - name: authentication user
          credentials:
            username: rajif@gmail.com
            password: mypassword
  vars: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - name: passiveScan-config
    type: passiveScan-config
    parameters:
      scanOnlyInScope: true
      enableTags: false
    rules: []

  # openapi job DISABLED
  # - name: openapi
  #   type: openapi
  #   parameters:
  #     definitionUrl: http://13.212.48.92:4003/swagger
  #     context: Default Context

  - name: passiveScan-wait
    type: passiveScan-wait
    parameters: {}

  - name: activeScan
    type: activeScan
    parameters:
      context: Default Context
      threadPerHost: 4
      user: authentication user
    policyDefinition:
      rules: []
