env:
  contexts:
    - name: Default Context
      urls:
        - http://13.212.48.92:4003
      includePaths:
        - http://13.212.48.92:4003.*
      excludePaths: []
      authentication:
        method: form
        parameters:
          loginPageUrl: http://13.212.48.92:4003/api/auth/login
          loginRequestUrl: http://13.212.48.92:4003/api/auth/login
          loginRequestBody: username={%username%}&password={%password%}
        verification:
          method: poll
          pollUrl: http://13.212.48.92:4003/api/auth/login
          pollFrequency: 60
          pollUnits: requests
          loggedInRegex: Login
          loggedOutRegex: Logout  # <== FIX typo sebelumnya
      sessionManagement:
        method: cookie
        parameters: {}
      users:
        - name: authentication user
          credentials:
            username: rajif@gmail.com
            password: mypassword

  vars: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - name: passiveScan-config
    type: passiveScan-config
    parameters:
      scanOnlyInScope: true
      enableTags: false

  - name: openapi
    type: openapi
    parameters:
      context: Default Context
      definitionUrl: http://13.212.48.92:4003/swagger  # <== Ganti dari `apiFile` ke `definitionUrl`

  - name: passiveScan-wait
    type: passiveScan-wait
    parameters: {}

  - name: activeScan
    type: activeScan
    parameters:
      context: Default Context
      user: authentication user
      threadPerHost: 4
    policyDefinition:
      rules: []
