env:
  contexts:
    - name: Default Context
      includePaths:
        - http://34.134.193.94:5000.*
      excludePaths: []
      urls:
        - http://34.134.193.94:5000
      technology:
        exclude: []
      authentication:
        method: json
        parameters:
          loginPageUrl: http://34.134.193.94:5000
          loginRequestUrl: http://34.142.219.174:5000/api/auth/login
          loginRequestBody: '{ "email": "%username%", "password": "%password%" }'
        verification:
          method: poll
          pollUrl: http://34.142.219.174:5000
          pollFrequency: 60
          pollUnits: requests
          loggedInRegex: '"token"\s*:\s*".+?"'
          loggedOutRegex: '"logout"'
      sessionManagement:
        method: httpHeader
        parameters:
            headerName: Authorization

      users:
        - name: authentication user
          credentials:
            username: naomi123@gmail.com
            password: password

vars: {}
parameters:
  failOnError: true
  failOnWarning: false
  progressToStdout: true

jobs:
-
    parameters:
        scanOnlyInScope: true
        enableTags: false
    rules: []
    name: passiveScan-config
    type: passiveScan-config
-
    name: openapi
    parameters:
        apiFile: http://54.179.2.8:4002/swagger
        context: Default Context
    type: openapi
-
    parameters: {}
    name: passiveScan-wait
    type: passiveScan-wait
-
    parameters:
        context: Default Context
        threadPerHost: 4
        user: authentication user
    policyDefinition:
        rules: []
    name: activeScan
    type: activeScan
-
    parameters:
        template: traditional-pdf
        reportDir: ''
        reportTitle: ZAP Scanning Report
        reportDescription: ''
    name: report-pdf
    type: report
