---
env:
  contexts:
  - name: "Default Context"
    urls:
    - http://34.142.219.174:5000.*
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: headers
      parameters:
        Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0MDM5MTY0MywiZXhwIjoxNzQwMzk1MjQzfQ.ov1JEkc7Uz5mv7_y_oK3FIOFvTFDfdykRe019C4dppE
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "openapi"
  type: "openapi"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters: {}
  policyDefinition:
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "risk-confidence-html"
    reportTitle: "ZAP Jira Cloud Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"

