openapi: 3.0.1
info:
  title: REST API
  description: ""
  version: 1.0.0
servers:
- url: http://13.212.48.92:4003/
paths:
  /swagger:
    get:
      responses:
        "200":
          description: OK
          content: {}
  /api/auth/register:
    post:
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                email:
                  type: object
                  example: any
                password:
                  type: object
                  example: any
        required: false
      responses:
        "201":
          description: Created
          content: {}
        "400":
          description: Bad Request
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /api/auth/login:
    post:
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                email:
                  type: object
                  example: any
                password:
                  type: object
                  example: any
        required: false
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad Request
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /api/order/:
    get:
      parameters:
      - name: authorization
        in: header
        schema:
          type: string
      responses:
        "200":
          description: OK
          content: {}
        "400":
          description: Bad Request
          content: {}
        "401":
          description: Unauthorized
          content: {}
        "403":
          description: Forbidden
          content: {}
        "500":
          description: Internal Server Error
          content: {}
    post:
      parameters:
      - name: authorization
        in: header
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                name:
                  type: object
                  example: any
                quantity:
                  type: object
                  example: any
        required: false
      responses:
        "201":
          description: Created
          content: {}
        "401":
          description: Unauthorized
          content: {}
        "403":
          description: Forbidden
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
components: {}
x-original-swagger-version: "2.0"
